# coding: utf-8

"""
    Reporte de Crédito Consolidado, FICO® Score y PLD - Simulación

    <p>Esta API simula: el reporte del historial crediticio; el cumplimiento de pago de los compromisos que la persona ha adquirido con entidades financieras, no financieras e instituciones comerciales que dan crédito o participan en actividades afines al crédito; y filtra contra listas de cumplimiento para Prevención de Lavado de Dinero. En esta versión se retornan los campos del Crédito Asociado a Nomina (CAN) en el nodo de créditos.<br/><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: api@circulodecredito.com.mx
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rcc_fico_pld_simulacion_client
from rcc_fico_pld_simulacion_client.api.reporte_de_crdito_consolidado_fico_score_y_pld_api import ReporteDeCrditoConsolidadoFICOScoreYPLDApi
from rcc_fico_pld_simulacion_client.api_client import ApiClient
from rcc_fico_pld_simulacion_client.configuration import Configuration
from rcc_fico_pld_simulacion_client.models.catalogo_tipo_asentamiento import CatalogoTipoAsentamiento
from rcc_fico_pld_simulacion_client.models.catalogo_tipo_domicilio import CatalogoTipoDomicilio
from rcc_fico_pld_simulacion_client.models.domicilio_peticion import DomicilioPeticion
from rcc_fico_pld_simulacion_client.models.persona_peticion import PersonaPeticion  # noqa: E501
from rcc_fico_pld_simulacion_client.rest import ApiException


import configparser


class TestReporteDeCrditoConsolidadoFICOScoreYPLDApi(unittest.TestCase):
    x_api_key = ""
    host = ""

    def setUp(self):
        config = configparser.ConfigParser()
        config.read('config.ini')
        self.host = self.key_password= config['API_CONFIG']['host']
        self.x_api_key = self.key_password= config['API_CONFIG']['x_api_key']
    
        configuration = Configuration(host=self.host)
        self.api = ReporteDeCrditoConsolidadoFICOScoreYPLDApi(ApiClient(configuration))  # noqa: E501
    
   

    def test_get_reporte(self):
        body = PersonaPeticion(
            apellido_paterno="SESENTAYDOS",
            apellido_materno="PRUEBA",
            apellido_adicional=None,
            primer_nombre="JUAN",
            segundo_nombre=None,
            fecha_nacimiento="1965-08-09",
            rfc="SEPJ650809JG1",
            curp=None,
            nacionalidad="MX",
            residencia=None,
            estado_civil=None,
            sexo=None,
            clave_elector_ife=None,
            numero_dependientes=None,
            fecha_defuncion=None,
            domicilio=DomicilioPeticion( 
                direccion="PASADISO ENCONTRADO 58",
                colonia_poblacion="MONTEVIDEO", 
                delegacion_municipio="GUSTAVO A MADERO", 
                ciudad= "CIUDAD DE MÉXICO", 
                estado="CDMX", 
                cp="07730", 
                fecha_residencia=None, 
                numero_telefono=None, 
                tipo_domicilio=None, 
                tipo_asentamiento=None)
        )
        try:
   
            api_response=self.api.get_reporte( x_api_key=self.x_api_key,  request=body,x_full_report=True)
            print(api_response)
        except ApiException as e:
            print("Exception when calling TestReporteDeCrditoConsolidadoFICOScoreYPLDApi->test_get_reporte: %s\n" % e)



if __name__ == '__main__':
    unittest.main()
