# coding: utf-8


import pprint
import re  # noqa: F401

import six

from rcc_fico_pld_simulacion_client.configuration import Configuration


class CatalogoTipoCredito(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AA = "AA"
    AB = "AB"
    AE = "AE"
    AM = "AM"
    AR = "AR"
    AV = "AV"
    BC = "BC"
    BL = "BL"
    BR = "BR"
    CA = "CA"
    CC = "CC"
    CF = "CF"
    CO = "CO"
    CP = "CP"
    ED = "ED"
    EQ = "EQ"
    FF = "FF"
    FI = "FI"
    FT = "FT"
    GS = "GS"
    HB = "HB"
    HE = "HE"
    HV = "HV"
    LC = "LC"
    LR = "LR"
    MC = "MC"
    NG = "NG"
    PB = "PB"
    PC = "PC"
    PE = "PE"
    PG = "PG"
    PQ = "PQ"
    PM = "PM"
    PN = "PN"
    PP = "PP"
    SH = "SH"
    TC = "TC"
    TD = "TD"
    TG = "TG"
    TS = "TS"
    VR = "VR"
    OT = "OT"
    NC = "NC"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self, _configuration=None):  # noqa: E501
        """CatalogoTipoCredito - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CatalogoTipoCredito, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CatalogoTipoCredito):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CatalogoTipoCredito):
            return True

        return self.to_dict() != other.to_dict()
